-- Britannia Snackin: realtime campaign backend
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  spot_number bigint generated by default as identity (start with 1 increment by 1),
  instagram_handle text,
  image_path text not null,
  slot_index integer not null,
  created_at timestamptz not null default now()
);

create index if not exists participants_spot_idx on public.participants(spot_number);
create index if not exists participants_created_idx on public.participants(created_at desc);
create index if not exists participants_handle_idx on public.participants(lower(instagram_handle));

alter table public.participants enable row level security;

drop policy if exists "public can read participants" on public.participants;
create policy "public can read participants"
on public.participants for select
using (true);

-- Public read is enough for the microsite. Inserts happen only through the RPC below.
drop policy if exists "public can insert participants" on public.participants;

create or replace function public.claim_snackin(
  p_instagram_handle text,
  p_image_path text
)
returns public.participants
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.participants;
  v_spot bigint;
begin
  if p_image_path is null or length(trim(p_image_path)) = 0 then
    raise exception 'image_path is required';
  end if;

  insert into public.participants(instagram_handle, image_path, slot_index)
  values (
    nullif(trim(p_instagram_handle), ''),
    p_image_path,
    0
  )
  returning * into v_row;

  update public.participants
  set slot_index = mod(v_row.spot_number - 1, 4096)::integer
  where id = v_row.id
  returning * into v_row;

  return v_row;
end;
$$;

grant execute on function public.claim_snackin(text,text) to anon, authenticated;

grant select on public.participants to anon, authenticated;

-- Storage bucket for voluntarily submitted participant photos.
insert into storage.buckets (id, name, public)
values ('faces', 'faces', true)
on conflict (id) do update set public = true;

drop policy if exists "public can upload campaign faces" on storage.objects;
create policy "public can upload campaign faces"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'faces');

drop policy if exists "public can view campaign faces" on storage.objects;
create policy "public can view campaign faces"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'faces');

-- Enable Realtime for the participant table (safe to run more than once).
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'participants'
  ) then
    alter publication supabase_realtime add table public.participants;
  end if;
end $$;
